#!/bin/bash
branch=${1}

for i in openembedded-core yocto-docs meta-yocto bitbake; do
	echo $i
	if [ $branch != "master" -a $i = "bitbake" ]; then
		if [ $branch = "kirkstone" ]; then
			branch="2.0"
		elif [ $branch = "scarthgap" ]; then
			branch="2.8"
		elif [ $branch = "walnascar" ]; then
			branch="2.12"
		else
			continue;
		fi
	fi
    
	cd ~/Repos/$i
	git checkout $branch
	git pull
done

cd ~/Repos/poky

branch=${1}
git checkout $branch
../poky-config/combo-layer -c ../poky-config/combo-layer-$branch.conf -n update
