#!/bin/sh
BRANCH=$1

if [ -z $BRANCH ]; then
    BRANCH=master
fi

RECIPE="meta/recipes-core/images/build-appliance-image_15.0.0.bb"

HEAD=`cd ../poky; git log $BRANCH --pretty=%H -n 1`
echo "$BRANCH HEAD is $HEAD"
(
    cd ../openembedded-core
    git checkout $BRANCH
    sed -i -e "s/^SRCREV ?= \".*\"/SRCREV ?= \"$HEAD\"/" $RECIPE
    sed -i -e "s#\(git://git.yoctoproject.org/poky;branch=\).*\( \\)#\1$BRANCH\2#" $RECIPE
    git commit -m "build-appliance-image: Update to $BRANCH head revision"  -as
)
