#!/bin/bash

for b in kirkstone scarthgap walnascar; do
	for i in openembedded-core bitbake meta-yocto yocto-docs poky; do
		echo Syncing $i ...
		branch=$b
		if [ $branch != "master" -a $i = "bitbake" ]; then
			if [ $branch = "kirkstone" ]; then
				branch="2.0"
			elif [ $branch = "scarthgap" ]; then
				branch="2.8"
			elif [ $branch = "walnascar" ]; then
				branch="2.12"
			else
				continue;
			fi
		fi
    
		cd ~/Repos/$i
		git checkout $branch
		git pull
	done
done
